# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/primi/src/latino-llvm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/primi/src/latino-llvm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"latinoBasic\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/primi/src/latino-llvm/CMakeFiles /home/primi/src/latino-llvm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/primi/src/latino-llvm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticRefactoring

# Build rule for target.
ClangDiagnosticRefactoring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticRefactoring
.PHONY : ClangDiagnosticRefactoring

# fast build rule for target.
ClangDiagnosticRefactoring/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticRefactoring.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticRefactoring.dir/build
.PHONY : ClangDiagnosticRefactoring/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticCommon

# Build rule for target.
ClangDiagnosticCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticCommon
.PHONY : ClangDiagnosticCommon

# fast build rule for target.
ClangDiagnosticCommon/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticCommon.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticCommon.dir/build
.PHONY : ClangDiagnosticCommon/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticSema

# Build rule for target.
ClangDiagnosticSema: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticSema
.PHONY : ClangDiagnosticSema

# fast build rule for target.
ClangDiagnosticSema/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticSema.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticSema.dir/build
.PHONY : ClangDiagnosticSema/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticSerialization

# Build rule for target.
ClangDiagnosticSerialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticSerialization
.PHONY : ClangDiagnosticSerialization

# fast build rule for target.
ClangDiagnosticSerialization/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticSerialization.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticSerialization.dir/build
.PHONY : ClangDiagnosticSerialization/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticGroups

# Build rule for target.
ClangDiagnosticGroups: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticGroups
.PHONY : ClangDiagnosticGroups

# fast build rule for target.
ClangDiagnosticGroups/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticGroups.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticGroups.dir/build
.PHONY : ClangDiagnosticGroups/fast

#=============================================================================
# Target rules for targets named ClangDiagnosticIndexName

# Build rule for target.
ClangDiagnosticIndexName: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangDiagnosticIndexName
.PHONY : ClangDiagnosticIndexName

# fast build rule for target.
ClangDiagnosticIndexName/fast:
	$(MAKE) -f include/latino/Basic/CMakeFiles/ClangDiagnosticIndexName.dir/build.make include/latino/Basic/CMakeFiles/ClangDiagnosticIndexName.dir/build
.PHONY : ClangDiagnosticIndexName/fast

#=============================================================================
# Target rules for targets named ClangAttrParsedAttrList

# Build rule for target.
ClangAttrParsedAttrList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrParsedAttrList
.PHONY : ClangAttrParsedAttrList

# fast build rule for target.
ClangAttrParsedAttrList/fast:
	$(MAKE) -f include/latino/Sema/CMakeFiles/ClangAttrParsedAttrList.dir/build.make include/latino/Sema/CMakeFiles/ClangAttrParsedAttrList.dir/build
.PHONY : ClangAttrParsedAttrList/fast

#=============================================================================
# Target rules for targets named ClangAttrParsedAttrImpl

# Build rule for target.
ClangAttrParsedAttrImpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrParsedAttrImpl
.PHONY : ClangAttrParsedAttrImpl

# fast build rule for target.
ClangAttrParsedAttrImpl/fast:
	$(MAKE) -f include/latino/Sema/CMakeFiles/ClangAttrParsedAttrImpl.dir/build.make include/latino/Sema/CMakeFiles/ClangAttrParsedAttrImpl.dir/build
.PHONY : ClangAttrParsedAttrImpl/fast

#=============================================================================
# Target rules for targets named ClangAttrTemplateInstantiate

# Build rule for target.
ClangAttrTemplateInstantiate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrTemplateInstantiate
.PHONY : ClangAttrTemplateInstantiate

# fast build rule for target.
ClangAttrTemplateInstantiate/fast:
	$(MAKE) -f include/latino/Sema/CMakeFiles/ClangAttrTemplateInstantiate.dir/build.make include/latino/Sema/CMakeFiles/ClangAttrTemplateInstantiate.dir/build
.PHONY : ClangAttrTemplateInstantiate/fast

#=============================================================================
# Target rules for targets named ClangAttrSpellingListIndex

# Build rule for target.
ClangAttrSpellingListIndex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrSpellingListIndex
.PHONY : ClangAttrSpellingListIndex

# fast build rule for target.
ClangAttrSpellingListIndex/fast:
	$(MAKE) -f include/latino/Sema/CMakeFiles/ClangAttrSpellingListIndex.dir/build.make include/latino/Sema/CMakeFiles/ClangAttrSpellingListIndex.dir/build
.PHONY : ClangAttrSpellingListIndex/fast

#=============================================================================
# Target rules for targets named ClangAttrParsedAttrKinds

# Build rule for target.
ClangAttrParsedAttrKinds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrParsedAttrKinds
.PHONY : ClangAttrParsedAttrKinds

# fast build rule for target.
ClangAttrParsedAttrKinds/fast:
	$(MAKE) -f include/latino/Sema/CMakeFiles/ClangAttrParsedAttrKinds.dir/build.make include/latino/Sema/CMakeFiles/ClangAttrParsedAttrKinds.dir/build
.PHONY : ClangAttrParsedAttrKinds/fast

#=============================================================================
# Target rules for targets named ClangAttrPCHWrite

# Build rule for target.
ClangAttrPCHWrite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrPCHWrite
.PHONY : ClangAttrPCHWrite

# fast build rule for target.
ClangAttrPCHWrite/fast:
	$(MAKE) -f include/latino/Serialization/CMakeFiles/ClangAttrPCHWrite.dir/build.make include/latino/Serialization/CMakeFiles/ClangAttrPCHWrite.dir/build
.PHONY : ClangAttrPCHWrite/fast

#=============================================================================
# Target rules for targets named ClangAttrPCHRead

# Build rule for target.
ClangAttrPCHRead: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangAttrPCHRead
.PHONY : ClangAttrPCHRead

# fast build rule for target.
ClangAttrPCHRead/fast:
	$(MAKE) -f include/latino/Serialization/CMakeFiles/ClangAttrPCHRead.dir/build.make include/latino/Serialization/CMakeFiles/ClangAttrPCHRead.dir/build
.PHONY : ClangAttrPCHRead/fast

#=============================================================================
# Target rules for targets named latinoBasic

# Build rule for target.
latinoBasic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 latinoBasic
.PHONY : latinoBasic

# fast build rule for target.
latinoBasic/fast:
	$(MAKE) -f lib/Basic/CMakeFiles/latinoBasic.dir/build.make lib/Basic/CMakeFiles/latinoBasic.dir/build
.PHONY : latinoBasic/fast

#=============================================================================
# Target rules for targets named latino

# Build rule for target.
latino: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 latino
.PHONY : latino

# fast build rule for target.
latino/fast:
	$(MAKE) -f tools/driver/CMakeFiles/latino.dir/build.make tools/driver/CMakeFiles/latino.dir/build
.PHONY : latino/fast

#=============================================================================
# Target rules for targets named LatinoUnitTests

# Build rule for target.
LatinoUnitTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LatinoUnitTests
.PHONY : LatinoUnitTests

# fast build rule for target.
LatinoUnitTests/fast:
	$(MAKE) -f unittests/CMakeFiles/LatinoUnitTests.dir/build.make unittests/CMakeFiles/LatinoUnitTests.dir/build
.PHONY : LatinoUnitTests/fast

#=============================================================================
# Target rules for targets named BasicTests

# Build rule for target.
BasicTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicTests
.PHONY : BasicTests

# fast build rule for target.
BasicTests/fast:
	$(MAKE) -f unittests/Basic/CMakeFiles/BasicTests.dir/build.make unittests/Basic/CMakeFiles/BasicTests.dir/build
.PHONY : BasicTests/fast

#=============================================================================
# Target rules for targets named LexTests

# Build rule for target.
LexTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LexTests
.PHONY : LexTests

# fast build rule for target.
LexTests/fast:
	$(MAKE) -f unittests/Lex/CMakeFiles/LexTests.dir/build.make unittests/Lex/CMakeFiles/LexTests.dir/build
.PHONY : LexTests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... intrinsics_gen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... ClangDiagnosticRefactoring"
	@echo "... ClangDiagnosticCommon"
	@echo "... ClangDiagnosticSema"
	@echo "... ClangDiagnosticSerialization"
	@echo "... ClangDiagnosticGroups"
	@echo "... ClangDiagnosticIndexName"
	@echo "... ClangAttrParsedAttrList"
	@echo "... ClangAttrParsedAttrImpl"
	@echo "... ClangAttrTemplateInstantiate"
	@echo "... ClangAttrSpellingListIndex"
	@echo "... ClangAttrParsedAttrKinds"
	@echo "... ClangAttrPCHWrite"
	@echo "... ClangAttrPCHRead"
	@echo "... latinoBasic"
	@echo "... latino"
	@echo "... LatinoUnitTests"
	@echo "... BasicTests"
	@echo "... LexTests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

