//===--- Sema.h - Semantic Analysis & AST Building --------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines the Sema class, which performs semantic analysis and
// builds ASTs.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LATINO_SEMA_SEMA_H
#define LLVM_LATINO_SEMA_SEMA_H

#include "latino/AST/ASTContext.h"
#include "latino/AST/ASTConsumer.h"
#include "latino/Basic/Specifiers.h"
#include "latino/Sema/Scope.h"
#include "latino/Lex/Preprocessor.h"
#include "latino/Sema/CodeCompleteConsumer.h"
#include "latino/Sema/Scope.h"
#include "clang/Basic/LangOptions.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Frontend/OpenMP/OMPConstants.h"
#include <deque>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

namespace llvm {
  class APSInt;
  template <typename ValueT> struct DenseMapInfo;
  template <typename ValueT, typename ValueInfoT> class DenseSet;
  class SmallBitVector;
  struct InlineAsmIdentifierInfo;

}

namespace sema {

}

namespace latino {
/// Sema - This implements semantic analysis and AST building for C.
class Sema final {
  /// Flag indicating whether or not to collect detailed statistics.
  bool CollectStats;

  Sema(const Sema &) = delete;
  void operator=(const Sema &) = delete;

  /// A key method to reduce duplicate debug info from Sema.
  virtual void anchor();

  /// WeakTopLevelDecl - Translation-unit scoped declarations generated by
  /// \#pragma weak during processing of other Decls.
  /// I couldn't figure out a clean way to generate these in-line, so
  /// we store them here and handle separately -- which is a hack.
  /// It would be best to refactor this.
  SmallVector<Decl *, 2> WeakTopLevelDecl;

private:
  /// The parser's current scope.
  ///
  /// The parser maintains this state here.
  Scope *CurScope;

  /// The kind of translation unit we are processing.
  ///
  /// When we're processing a complete translation unit, Sema will perform
  /// end-of-translation-unit semantic tasks (such as creating
  /// initializers for tentative definitions in C) once parsing has
  /// completed. Modules and precompiled headers perform different kinds of
  /// checks.
  clang::TranslationUnitKind TUKind;

    /// Code-completion consumer.
  CodeCompleteConsumer *CodeCompleter;

public:
  Preprocessor &PP;
  ASTContext &Context;
  ASTConsumer &Consumer;

  /// Retrieve the parser's current scope.
  ///
  /// This routine must only be used when it is certain that semantic analysis
  /// and the parser are in precisely the same context, which is not the case
  /// when, e.g., we are performing any kind of template instantiation.
  /// Therefore, the only safe places to use this scope are in the parser
  /// itself and in routines directly invoked from the parser and *never* from
  /// template substitution or instantiation.
  Scope *getCurScope() const { return CurScope; }

  Preprocessor &getPreprocessor() const { return PP; }
  ASTConsumer &getASTConsumer() const { return Consumer; }

  void incrementMSManglingNumber() const {
    return CurScope->incrementMSManglingNumber();
  }

  /// Retrieve the keyword associated
  IdentifierInfo *getNullabilityKeyword(NullabilityKind nullability);

  public:
  Sema(Preprocessor &pp, ASTContext &ctxt, ASTConsumer &consumer,
       clang::TranslationUnitKind TUKind = clang::TU_Complete,
       CodeCompleteConsumer *CompletionConsumer = nullptr);
  ~Sema();

  // void PrintStats() const;
  ASTContext &getASTContext() const { return Context; }

  /// WeakTopLevelDeclDecls - access to \#pragma weak-generated Decls
  SmallVectorImpl<Decl *> &WeakTopLevelDecls() { return WeakTopLevelDecl; }
};
} // namespace latino

#endif